### ISSUE TITLE
Auto-index functions

### ISSUE THREAD

**Issue by quickfold** [retorquere/zotero-auto-index#4] opened 2014-07-31 03:33 UTC
I don't index every item as I add it because it disrupts my workflow to have Zotero freeze for 1-2 minutes each time I add an attachment.

I think the most useful indexing improvement would be to have Zotero index when it is not being actively used, and 1) index only a limited number of items at a time or 2) stop indexing when the user starts interacting with it so it is ready and available next time the user wants to use it.

I hope you will be interested in developing such an add-on or adding this functionality to Zotero Auto-Index!

**Comment by quickfold** [comment] 2015-02-28 18:18
Hi, so when the current version, is installed, does Zotero:
1. not index attachments when manually added to items
2. not index attachments until Zotero has been idle for X minutes
3. automatically index attachments when Zotero has been idle for X minutes
Is that the behavior? And if so, does Zotero still not index items when manually added even if prefs are not set to zero?
Thanks!

**Comment by AllThatIsTheCase** [comment] 2015-02-28 20:51
I don't interfere with anything Zotero might be doing on it's own. I don't think Zotero automatically indexes attachments, it's always on-demand. 

X seconds after Firefox becomes idle, the plugin will start indexing un-indexed attachments. When FF leaves idle state, it will finish the current index job, and than wait again for idle. 

You can also have the plugin mark everything as un-indexed when the Zotero indexing parameters change (max length/max pages), but that isn't enabled by default, you need to set the hidden pref `auto-index.reindexOnPrefChange`.

Which prefs do you mean with 'set to zero'?

**Comment by quickfold** [comment] 2015-03-02 17:11
Actually, Zotero does automatically index attachments. If you have prefs 
in Options/Search set to something other than zero pages and zero 
characters, then every time you add an attachment to Zotero it will 
immediately begin to index it. That's why I was asking about this. I 
think your add-on is mostly useful (currently) for people with big 
libraries who don't have any of them indexed. I am hoping it can also be 
useful for people like me who have large indexed libraries and want to 
fully auto-index new attachments when they are not actively using 
Zotero, because indexing books and such takes a long time, during which 
Zotero is frozen.

**Comment by AllThatIsTheCase** [comment] 2015-03-02 17:22
Ah, I see. I'll look into this, but Zotero doesn't make this entirely easy.

**Comment by AllThatIsTheCase** [comment] 2015-03-12 09:45
Turns out that the current behavior already accomplishes this. *All* indexing is deferred until idle.

**Comment by AllThatIsTheCase** [comment] 2015-03-12 09:45
Is this not what you see? Because that would be a bug.

**Comment by quickfold** [comment] 2015-03-12 14:38
That is not what I see. Where did you get the information that all indexing was idle?  Does that work for you as indexing only when idle? On Thu, Mar 12, 2015 at 4:45 AM,  ZotPlus/zotero-auto-index <reply@reply.github.com> wrote:            Is this not what you see? Because that would be a bug.

**Comment by AllThatIsTheCase** [comment] 2015-03-12 16:46
I can see in the logs that when I add a PDF to an entry, Zotero attempts to index but this attempt is blocked, as Firefox isn't idle. When the idle processor kicks off, the attempt is restarted. What do you do that kicks off indexing, and how do you notice it is actually indexing? Is the attachment status indexed after adding? It isn't for me.

**Comment by quickfold** [comment] 2015-03-12 19:18
I just realized that I'm using Zotero stand-alone and that might be the 
difference. (I'm also on Win 7 x64).

Without auto-index installed, and max pages/characters set at some high 
number, I find that when I add an attachment Zotero is unresponsive / 
hangs for a while until the indexing is done. It eventually unfreezes 
and the attachment shows as indexed.

**Comment by AllThatIsTheCase** [comment] 2015-03-12 23:13
Ugh, Zotero indexing is really woven very deeply into Zotero. I can interrupt this, but you won't be able to manually kick off indexing at all unless you disable temporarily.

**Comment by AllThatIsTheCase** [comment] 2015-03-13 09:06
I've just released .36, which has a few simplifications. After installing it and restarting, go into preferences->advanced and click "enable". Now add an attachment, go to preferences->advanced again, and click "view". If you search the log (control-F) you will find lines with [auto-index]; the newly added file should be there, followed by ":false", meaning an attempt at indexing was started but not actually performed. Now let your computer (not just firefox) sit idle for the timeout period you set (60 seconds by default), and the log (after closing and re-opening it, it doesn't so live refresh) should have a line that ends in ":true", and the indexing state in the UI should reflect this.

The manual refresh button won't do anything, as by definition your computer won't be idle as you click it, but I haven't been able to find a way yet to hide that button.

**Comment by AllThatIsTheCase** [comment] 2015-03-13 09:13
Standalone shouldn't make a difference (I've tried), and I use Win8 x64 on my desktops myself, so I don't think that should be the cause. Let's see what you find in your logs, it will tell us more.

**Comment by retorquere** [comment] 2016-08-07 08:19
Closing for inactivity.

**Closed by retorquere** 2016-08-07 08:19 UTC
